# docker-compose.yml specific for python flask usage
# * exposing port 80 for the application
# * exposing port 3000 for the debugger
version: '3'

services:
  web:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    # command: bash
    environment: 
      FLASK_APP: main.py
      FLASK_DEBUG: 1
      FLASK_ENV: "development"
      # We use ptvsd instead
      FLASK_DEBUG: "0"
    volumes: 
      - "./src:/src"
    ports:
      - '80:80'
      - '3000:3000'